### PR TITLE
Support user-defined driverPath

### PR DESCRIPTION
**Pull request by lhoggatt17**
This allows support for chromium and probably other chrome-based browsers (but I haven't tested other ones). I made this modification locally so I can use this awesome library on my raspberry pi with chromium.

### CODE REVIEW

**Comment by aktur** [comment]
Will this pull request be integrated anytime soon? I'm asking this because I need this to get it running on AWS lambda and not sure if I can wait for integration or just go with own fork?

**Review by BipedOyster0 — APPROVED** [review]

**Comment by WieeRd** [comment]
Merge this already...

**Review by RamishSiddiqui — APPROVED** [review]

**Review by nateshmbhat — APPROVED** [review]

**Comment by nateshmbhat** [comment]
Thank you for your contributions.

**Comment by nateshmbhat** [comment]
Thank you for your contributions.

**Pull request merged**
