### PR TITLE
Update project to better match PEP 8 rules.

### PR DESCRIPTION
**Pull request by Paszymaja**
- reformat code to match PEP 8
- deleted semicolons
- optimised imports
- removed redundant parentheses
- updated deprecated selenium code
- made docstrings more readable
- changed self.error to [] because it's faster
- fixed gramma

### CODE REVIEW

**Review by BlackFalcons — APPROVED** [review]
Good job, this is long needed for this project.

**Comment by Paszymaja** [comment]
but what @nateshmbhat thinks ;)

**Comment by nateshmbhat** [comment]
Hey thanks so much for your contribution. I will review these changes in a week or so. Fully Occupied with work right now.

Meanwhile can u tell me about how u applied the code changes as per pep8 ? Did u change it manually or used a tool or something ?

**Comment by Paszymaja** [comment]
I used jetbrains pycharm built in refactor tools and some things (semicolons, deprecated selenium code)  I changed by hand.

**Review by KrzysztofZawisla — APPROVED** [review]

**Comment by nateshmbhat** [comment]
@Paszymaja can u resolve the conflicts in this branch?

**Comment by Paszymaja** [comment]
@nateshmbhat I resolved the conflicts.

**Review by nateshmbhat — APPROVED** [review]
lgtm

**Comment by nateshmbhat** [comment]
Thank you so much for your wonderful contribution 🥳 😄

**Pull request merged**
